const $ = s => document.querySelector(s);
const STORE='eduvanta_topics_v1', SESSION='eduvanta_admin_session_v1', ADMIN_PASSWORD='Manabraj';
const readTopics=()=>{try{const d=JSON.parse(localStorage.getItem(STORE)||'[]');return Array.isArray(d)?d:[]}catch{return[]}};
const saveTopics=t=>localStorage.setItem(STORE,JSON.stringify(t));
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function showDash(){ $('#loginView').classList.add('hidden'); $('#dashboard').classList.remove('hidden'); loadTopics(); }
function loadTopics(){const box=$('#adminTopics'); const topics=readTopics(); box.innerHTML=topics.length?topics.map(t=>`<article class="admin-topic"><div><strong>${esc(t.title)}</strong><small>${esc(t.month)} • ${t.questions.length} প্রশ্ন</small></div><div class="topic-actions"><a class="small-btn" href="Topic Answer.html?topic=${encodeURIComponent(t.id)}">View</a><button class="small-btn danger" data-id="${esc(t.id)}">Delete</button></div></article>`).join(''):'<div class="empty">এখনও কোনো Topic Publish করা হয়নি।</div>'; box.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{if(confirm('এই Topic delete করবেন?')){saveTopics(readTopics().filter(t=>t.id!==b.dataset.id));loadTopics();}});}
$('#loginForm').addEventListener('submit',e=>{e.preventDefault(); const msg=$('#loginMsg'); if($('#password').value===ADMIN_PASSWORD){sessionStorage.setItem(SESSION,'1'); $('#password').value=''; msg.textContent=''; showDash();}else{msg.textContent='পাসওয়ার্ড সঠিক নয়'; $('#password').focus();}});
$('#logoutBtn').addEventListener('click',()=>{sessionStorage.removeItem(SESSION);location.reload();});
$('#jsonFile').addEventListener('change',e=>$('#fileName').textContent=e.target.files[0]?.name||'ফাইল নির্বাচন করুন');
$('#publishForm').addEventListener('submit',async e=>{e.preventDefault();const file=$('#jsonFile').files[0],msg=$('#publishMsg');if(!file)return;try{const raw=JSON.parse(await file.text());const arr=Array.isArray(raw)?raw:raw.questions;if(!Array.isArray(arr))throw new Error('JSON-এ questions array পাওয়া যায়নি');const questions=arr.map(q=>({q:String(q.q??q.question??'').trim(),options:Array.isArray(q.options)?q.options.map(String):[],answer:Number(q.answer)})).filter(q=>q.q&&q.options.length>=2&&Number.isInteger(q.answer)&&q.answer>=0&&q.answer<q.options.length);if(!questions.length)throw new Error('Valid প্রশ্ন পাওয়া যায়নি');const title=$('#title').value.trim();if(!title)throw new Error('Topic title দিন');const topic={id:'topic-'+Date.now().toString(36),title,description:$('#description').value.trim(),month:$('#month').value.trim()||'Current Affairs',questions,updatedAt:new Date().toISOString()};saveTopics([topic,...readTopics()]);msg.textContent=`✓ ${questions.length}টি প্রশ্ন Publish হয়েছে`;e.target.reset();$('#fileName').textContent='ফাইল নির্বাচন করুন';loadTopics();}catch(err){msg.textContent=err.message||'Publish করা যায়নি';}});
$('#refreshBtn').addEventListener('click',loadTopics);
if(sessionStorage.getItem(SESSION)==='1')showDash();
